name: 'Publish npm Package'
description: 'Installs dependencies, runs prepack, and publishes the package to npm'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20'
  npm-token:
    description: 'NPM authentication token'
    required: true
  repository:
    description: 'Repository to checkout'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout helm chart repository
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.repository }}

    - name: Set up Node.js
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
      with:
        node-version: ${{ inputs['node-version'] }}

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run prepack script
      run: npm run prepack
      shell: bash

    - name: Publish package to npm
      uses: JS-DevTools/npm-publish@4b07b26a2f6e0a51846e1870223e545bae91c552 #v3
      with:
        token: ${{ inputs['npm-token'] }}
