name: "Lint and Test Helm Charts"
description: "An action to lint and test Helm charts using chart-testing and kind."
inputs:
  chartDirs:
    description: "Comma-separated list of root directories containing Helm charts."
    required: false
    default: "."
outputs:
  changed: 
    description: "Indicates if there are changed charts."
    value: ${{ steps.list-changed.outputs.changed }}
runs:
  using: "composite"
  steps:
    - name: Checkout helm chart repository
      uses: actions/checkout@v4 # v4.2.2
      with:
        fetch-depth: 0

    - name: Checkout Shared Workflows repository
      uses: actions/checkout@v4
      with:
        repository: MapColonies/shared-workflows-test
        path: shared-workflows

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.16.3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1

    - name: Run chart-testing (list-changed)
      id: list_changed
      shell: bash
      run: |
        changed=$(ct list-changed --chart-dirs ${{ inputs.chartDirs }} --target-branch ${{ github.event.repository.default_branch }} --config shared-workflows/.github/configs/ct.yaml)
        echo "changed=$changed"
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      shell: bash
      run: |
        ct lint 
        --chart-dirs ${{ inputs.chartDirs }} 
        --target-branch ${{ github.event.repository.default_branch }} 
        --config shared-workflows/.github/configs/ct.yaml 
        --lint-conf shared-workflows/.github/configs/lintconf.yaml

    - name: Create kind cluster
      if: steps.list-changed.outputs.changed == 'true'
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

    - name: Run chart-testing (install)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct install --chart-dirs "${{ inputs.chartDirs }}" --target-branch "${{ github.event.repository.default_branch }}"
      shell: bash
